"""replay — score what the pipeline WOULD decide against what the org ACTUALLY shipped.

Why this exists
---------------
Autonomy % measures how much work the agent is allowed to do alone. It says
nothing about whether it should have been. A system whose autonomy % climbs
while its disagreement rate climbs looks like success on every chart and loses
trust in a single incident.

Replay produces the missing number. Take decisions whose real-world outcome is
already known — merged PRs, human rulings already in the ledger — hide the
outcome, ask the pipeline to decide, then compare. The result is a per-class
disagreement rate grounded in what the organisation actually did.

This is also the fastest path to a credible demo: instead of waiting months to
accumulate precedent, replay manufactures the evidence base from history that
already exists, in minutes.

Honesty constraints (these are the point, not decoration)
---------------------------------------------------------
* A replay NEVER writes to the decision ledger. Scoring is a read-only
  projection; inventing ledger rows to make a metric look populated would
  corrupt the audit substrate this system exists to protect.
* A class with too few samples reports INSUFFICIENT, never a flattering number
  computed from n=2.
* `accuracy_score` on live ledger entries is currently 0.0 for every row —
  nothing has ever computed it. Replay does not pretend otherwise: entries that
  were never scored are reported as UNSCORED and excluded from rates, rather
  than being counted as agreements.
Configuration posture (NOT hardcoded)
--------------------------------------
Every threshold here is *governance*, not a constant. The finops bundle already
owns this shape (`AUTOPILOT-THRESHOLD-*` carry `defaults: {threshold: ...}`), so
replay reads its thresholds from the caller — which resolves them from the
team's pinned bundle — and falls back to conservative built-ins ONLY when no
policy is supplied. The fallbacks are deliberately strict: an unconfigured
system should under-grant autonomy, never over-grant it.

To change a threshold, change the bundle and roll the pin. Do not edit this file.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Iterable, Mapping, Optional

# Conservative fallbacks, used ONLY when the caller supplies no policy. These
# are not "the" thresholds — the bundle is. See ReplayPolicy.from_bundle().
DEFAULT_MIN_SAMPLES = 5
DEFAULT_DISAGREEMENT_CEILING = 0.10


@dataclass(frozen=True)
class ReplayPolicy:
    """Thresholds governing how replay judges a class.

    Sourced from the team's pinned bundle rules, so two teams on different
    bundle versions are judged by their own standards — the same way autopilot
    confidence thresholds already work.
    """

    min_samples: int = DEFAULT_MIN_SAMPLES
    disagreement_ceiling: float = DEFAULT_DISAGREEMENT_CEILING
    # Per-class overrides, e.g. {"phi-classification": 0.0} for zero tolerance.
    class_ceilings: Mapping[str, float] = field(default_factory=dict)
    # Classes that may never be autopiloted regardless of measured performance.
    # Populated from bundle rules carrying `phi_locked: true`.
    invariant_classes: frozenset[str] = frozenset()

    def ceiling_for(self, ambiguity_class: str) -> float:
        return self.class_ceilings.get(ambiguity_class, self.disagreement_ceiling)

    def is_invariant(self, ambiguity_class: str) -> bool:
        return ambiguity_class in self.invariant_classes

    @classmethod
    def from_bundle(cls, rules: Iterable[Mapping[str, Any]]) -> "ReplayPolicy":
        """Derive policy from resolved bundle rules.

        Reads the same `defaults:` shape finops already uses, so adding a
        `REPLAY-*` rule to a bundle changes behaviour with no code change:

            - id: REPLAY-MIN-SAMPLES
              defaults: {min_samples: 8}
            - id: REPLAY-CEILING-PHI
              ambiguity_class: phi-classification
              defaults: {disagreement_ceiling: 0.0}

        Any rule marked `phi_locked: true` contributes its class to the
        invariant set — so an invariant declared for enforcement is
        automatically an invariant for autonomy scoring, and the two can never
        drift apart.
        """
        min_samples = DEFAULT_MIN_SAMPLES
        ceiling = DEFAULT_DISAGREEMENT_CEILING
        class_ceilings: dict[str, float] = {}
        invariants: set[str] = set()

        for rule in rules or ():
            defaults = rule.get("defaults") or {}
            klass = rule.get("ambiguity_class")

            if rule.get("phi_locked") and klass:
                invariants.add(klass)

            if "min_samples" in defaults:
                try:
                    min_samples = max(1, int(defaults["min_samples"]))
                except (TypeError, ValueError):
                    pass

            if "disagreement_ceiling" in defaults:
                try:
                    value = float(defaults["disagreement_ceiling"])
                except (TypeError, ValueError):
                    continue
                if klass:
                    class_ceilings[klass] = value
                else:
                    ceiling = value

        return cls(
            min_samples=min_samples,
            disagreement_ceiling=ceiling,
            class_ceilings=class_ceilings,
            invariant_classes=frozenset(invariants),
        )


DEFAULT_POLICY = ReplayPolicy()


@dataclass(frozen=True)
class ReplayCase:
    """One historical decision with a known outcome."""
    entry_id: str
    ambiguity_class: str
    team_id: str
    # What the org actually did (ground truth).
    actual: str
    # What the pipeline proposed when the outcome was hidden.
    proposed: Optional[str] = None
    # Was the proposal made autonomously, or gated to a human?
    autopiloted: bool = False
    scored: bool = True


@dataclass
class ClassScore:
    ambiguity_class: str
    policy: ReplayPolicy = DEFAULT_POLICY
    total: int = 0
    scored: int = 0
    agreements: int = 0
    disagreements: int = 0
    autopiloted: int = 0
    autopilot_disagreements: int = 0

    @property
    def disagreement_rate(self) -> Optional[float]:
        """Overall disagreement. None when there is not enough evidence."""
        if self.scored < self.policy.min_samples:
            return None
        return self.disagreements / self.scored

    @property
    def autopilot_disagreement_rate(self) -> Optional[float]:
        """The number that actually matters: when the agent acted ALONE, how
        often was it wrong? A high overall rate is tolerable if the bad calls
        were all gated to humans. This isolates the unsupervised failures."""
        if self.autopiloted < self.policy.min_samples:
            return None
        return self.autopilot_disagreements / self.autopiloted

    @property
    def verdict(self) -> str:
        """Plain-language recommendation an operator can act on."""
        # An invariant is never eligible for autonomy, however well it scores.
        # Measuring it is still useful — a high disagreement rate on a gated
        # class means the agent's SUGGESTIONS are poor, which is worth knowing.
        if self.policy.is_invariant(self.ambiguity_class):
            return "INVARIANT — HUMAN ALWAYS"
        rate = self.autopilot_disagreement_rate
        if rate is None:
            if self.scored == 0:
                return "UNSCORED"
            return "INSUFFICIENT"
        if rate == 0.0:
            return "AUTONOMY EARNED"
        if rate <= self.policy.ceiling_for(self.ambiguity_class):
            return "AUTONOMY DEFENSIBLE"
        return "REVOKE AUTONOMY"


@dataclass
class ReplayReport:
    policy: ReplayPolicy = DEFAULT_POLICY
    classes: dict[str, ClassScore] = field(default_factory=dict)

    @property
    def total_scored(self) -> int:
        return sum(c.scored for c in self.classes.values())

    @property
    def overall_disagreement(self) -> Optional[float]:
        scored = self.total_scored
        if scored < self.policy.min_samples:
            return None
        return sum(c.disagreements for c in self.classes.values()) / scored

    @property
    def overall_autopilot_disagreement(self) -> Optional[float]:
        auto = sum(c.autopiloted for c in self.classes.values())
        if auto < self.policy.min_samples:
            return None
        bad = sum(c.autopilot_disagreements for c in self.classes.values())
        return bad / auto

    def classes_to_revoke(self) -> list[ClassScore]:
        """Classes where the agent is acting alone and getting it wrong."""
        return sorted(
            (c for c in self.classes.values() if c.verdict == "REVOKE AUTONOMY"),
            key=lambda c: -(c.autopilot_disagreement_rate or 0),
        )


def score_replay(
    cases: Iterable[ReplayCase], policy: ReplayPolicy = DEFAULT_POLICY
) -> ReplayReport:
    """Fold replay cases into a per-class report. Pure; no I/O, no writes."""
    report = ReplayReport(policy=policy)
    for case in cases:
        cls = report.classes.setdefault(
            case.ambiguity_class,
            ClassScore(ambiguity_class=case.ambiguity_class, policy=policy),
        )
        cls.total += 1

        # An unscored case is not an agreement. Counting "we never checked" as
        # "we agreed" is how a disagreement metric becomes a lie.
        if not case.scored or case.proposed is None:
            continue

        cls.scored += 1
        agreed = _equivalent(case.proposed, case.actual)
        if agreed:
            cls.agreements += 1
        else:
            cls.disagreements += 1

        if case.autopiloted:
            cls.autopiloted += 1
            if not agreed:
                cls.autopilot_disagreements += 1

    return report


def _equivalent(proposed: str, actual: str) -> bool:
    """Whether two resolutions mean the same thing.

    Deliberately conservative: normalises whitespace and case only. Fuzzy
    matching here would inflate the agreement rate, which is the one direction
    this metric must never be wrong in.
    """
    return " ".join(proposed.split()).casefold() == " ".join(actual.split()).casefold()


def cases_from_ledger(entries: list[dict[str, Any]]) -> list[ReplayCase]:
    """Build replay cases from live ledger entries.

    Ground truth is a human ruling on a specific decision card; the proposal
    under test is an autopilot decision on the SAME card. If the agent resolved
    the card the same way the human did, that is an agreement; divergence is a
    real, measurable disagreement that already happened in production.

    Why `card_id` and NOT `slot_value_hash`
    ---------------------------------------
    `slot_value_hash` looks like a slot identity but is not one: on live data it
    maps 1:1 onto `ambiguity_class` (18 hashes, 18 classes; one hash covers 63
    entries with 52 distinct resolutions across 31 runs). Pairing on it compares
    unrelated questions and reports ~100% disagreement — a metric that is not
    merely wrong but confidently wrong, which is the worst kind for a governance
    surface. `card_id` is the per-question identity (198 distinct), and it is
    what the comparison must key on.
    """
    by_card: dict[str, list[dict[str, Any]]] = {}
    for e in entries:
        card = e.get("card_id")
        if card:
            by_card.setdefault(card, []).append(e)

    def at(e: dict[str, Any]) -> str:
        return e.get("created_at") or ""

    cases: list[ReplayCase] = []
    for group in by_card.values():
        humans = sorted(
            (e for e in group if e.get("confidence_source") == "human"), key=at
        )
        if not humans:
            continue
        truth = humans[0]
        truth_text = (truth.get("resolution_text") or "").strip()
        if not truth_text:
            continue

        for e in group:
            if e is truth:
                continue
            if e.get("confidence_source") != "autopilot":
                continue
            cases.append(
                ReplayCase(
                    entry_id=e.get("id", "?"),
                    ambiguity_class=e.get("ambiguity_class") or "unknown",
                    team_id=e.get("team_id") or "unknown",
                    actual=truth_text,
                    proposed=(e.get("resolution_text") or "").strip() or None,
                    autopiloted=True,
                )
            )
    return cases
